### ISSUE TITLE
SbtRunConfiguration does not honor custom JVM args in SBT global settings

### ISSUE THREAD

**Issue by zhongjiewu** [JetBrains/intellij-scala#137] opened 2015-03-27 04:44 UTC
When the IDE run the "build project" task, that actually does ```/export/apps/jdk/JDK-1_8_0_5/bin/java -Xms512M -Xmx1024M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M -Dfile.encoding=UTF-8 -Dsbt.log.noformat=true -Djline.terminal=none -classpath /home/zwu/.sbt/liplay/sbt-launch.jar xsbt.boot.Boot test:compile```, it does not pick up additional JVM options specified in SBT global config(settings/Build, Execution, Deployment/Build Tools/SBT).

The build process use a file at `src/org/jetbrains/sbt/runner/SbtRunConfiguration.scala` and this file does not honor the SBT global config

**Comment by zhongjiewu** [comment] 2015-03-30 21:57
My current work around with issue is to create a custom SBT task running "test:compile" as "Configuration" and insert my custom JVM args into the task.
For all the test, I delete the original "make project" task and put this task into the "before task" list.

**Comment by zhongjiewu** [comment] 2015-04-10 23:17
Also see: https://youtrack.jetbrains.com/issue/SCL-8277 (filed Feb 10, 2015)

**Comment by ePak** [comment] 2015-06-10 02:55
Facing similar issue with options `-Dsbt.override.build.repos=true -Dsbt.repository.config=<path-to-file>`.

**Comment by sateeshpnv** [comment] 2015-07-21 08:18
Is there a work-around or fix for this problem? This seems to be a regression introduced in recent upgrades.

**Comment by nkly** [comment] 2015-07-23 09:20
Hi! Thanks for the report. I moved it to Youtrack: https://youtrack.jetbrains.com/issue/SCL-8950

**Closed by nkly** 2015-07-23 09:20 UTC
